---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml
 
- name: ON S'ASSURE QU'UN FICHIER docker-compose.yml EXISTE
  remote_user: "{{ secret.users.me.name }}"
  stat:
    path: /opt/docker/communication-stack/docker-compose.yml
  register: communication_stack_docker_compose

- name: SUPPRESSION DE LA STACK communication SI ELLE EXISTE
  remote_user: "{{ secret.users.me.name }}"
  shell:
    chdir: /opt/docker/communication-stack
    cmd: docker compose down
  when: communication_stack_docker_compose.stat.exists

- name: INSTALLATION DU FICHIER DE COMPOSITION
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/communication-stack/docker-compose.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
    # validate: docker compose -f %s config

- name: INSTALLATION DU FICHIER DES VARIABLES D'ENVIRONNEMENT DOCKER
  template:
    src: env.j2
    dest: /opt/docker/communication-stack/.env
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"

- name: INSTALLATION/CONFIGURATION DU CONTENEUR jellystat
  include_tasks: includes/docker/ntfy.yml

- name: DÃ‰MARRAGE DE LA STACK communication
  remote_user: "{{ secret.users.me.name }}"
  shell:
    chdir: /opt/docker/communication-stack
    cmd: docker compose up -d

- name: CHANGEMENT DES DROITS UTILISATEUR SUR L'ENSEMBLE DU DOSSIER /opt/docker/communication-stack
  file:
    dest: /opt/docker/communication-stack
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
    mode: "0777"
    recurse: true